language: node_js
node_js:
  - "8"
  - "10"
  - "11"
cache:
  directories:
    - ~/.npm
    - node_modules
addons:
  apt:
    update: true
install:
  - npm install codecov -g
  - npm install
script:
  - npm run build
  - npm test
after_success:
  - npx nyc report --reporter=text-lcov > coverage.lcov
  - codecov
